server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/libraydb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  flyway:
    enabled: true
    schemas: public
    check-location: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    mixed: true
  mvc:
    throw-exception-if-no-handler-found: true
    media-types:
      json: application/json;charset=UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  web:
    resources:
      add-mappings: false
security:
  jwt:
    secret: dGhpc19pc19hX3Zlcnlfc2VjdXJlX3NlY3JldF9rZXk=
    expiration: 3600000 # 1h em ms
springdoc:
  swagger-ui:
    path: /swagger-ui.html